### ISSUE TITLE
Bad Results

### ISSUE THREAD

**Issue by zhichaolei** [phil-bergmann/tracking_wo_bnw#64] opened 2020-03-07 10:12 UTC
INFO - main - Initializing object detector.
INFO - main - Tracking: MOT17-02-FRCNN
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 600/600 [03:48<00:00,  2.63it/s]
INFO - main - Tracks found: 183
INFO - main - Runtime for MOT17-02-FRCNN: 228.4 s.
INFO - main - Writing predictions to: /home/zclei14/tracking_wo_bnw-master/output/tracktor/MOT17/Tracktor++
INFO - main - Tracking: MOT17-04-FRCNN
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1050/1050 [06:44<00:00,  2.60it/s]
INFO - main - Tracks found: 121
INFO - main - Runtime for MOT17-04-FRCNN: 404.6 s.
INFO - main - Writing predictions to: /home/zclei14/tracking_wo_bnw-master/output/tracktor/MOT17/Tracktor++
INFO - main - Tracking: MOT17-05-FRCNN
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 837/837 [02:21<00:00,  5.90it/s]
INFO - main - Tracks found: 62
INFO - main - Runtime for MOT17-05-FRCNN: 142.0 s.
INFO - main - Writing predictions to: /home/zclei14/tracking_wo_bnw-master/output/tracktor/MOT17/Tracktor++
INFO - main - Tracking: MOT17-09-FRCNN
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 525/525 [03:17<00:00,  2.66it/s]
INFO - main - Tracks found: 7
INFO - main - Runtime for MOT17-09-FRCNN: 197.5 s.
INFO - main - Writing predictions to: /home/zclei14/tracking_wo_bnw-master/output/tracktor/MOT17/Tracktor++
INFO - main - Tracking: MOT17-10-FRCNN
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 654/654 [05:57<00:00,  1.83it/s]
INFO - main - Tracks found: 313
INFO - main - Runtime for MOT17-10-FRCNN: 357.5 s.
INFO - main - Writing predictions to: /home/zclei14/tracking_wo_bnw-master/output/tracktor/MOT17/Tracktor++
INFO - main - Tracking: MOT17-11-FRCNN
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 900/900 [07:55<00:00,  1.89it/s]
INFO - main - Tracks found: 89
INFO - main - Runtime for MOT17-11-FRCNN: 475.7 s.
INFO - main - Writing predictions to: /home/zclei14/tracking_wo_bnw-master/output/tracktor/MOT17/Tracktor++
INFO - main - Tracking: MOT17-13-FRCNN
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 750/750 [09:01<00:00,  1.39it/s]
INFO - main - Tracks found: 460
INFO - main - Runtime for MOT17-13-FRCNN: 541.5 s.
INFO - main - Writing predictions to: /home/zclei14/tracking_wo_bnw-master/output/tracktor/MOT17/Tracktor++
INFO - main - Tracking runtime for all sequences (without evaluation or image writing): 2347.1 s (2.3 Hz)
/home/zclei14/anaconda3/lib/python3.6/site-packages/motmetrics/mot.py:243: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  idx = pd.MultiIndex(levels=[[],[]], labels=[[],[]], names=['FrameId','Event'])
               IDF1  IDP  IDR Rcll Prcn  GT MT PT  ML     FP     FN IDs   FM    MOTA  MOTP
MOT17-02-FRCNN 1.3% 1.2% 1.4% 2.1% 1.9%  62  0  0  62  19961  18189  32   33 -105.5% 0.386
MOT17-04-FRCNN 0.1% 0.3% 0.1% 0.3% 0.9%  83  0  2  81  13828  47433  17   17  -28.9% 0.391
MOT17-05-FRCNN 1.1% 1.3% 0.9% 1.2% 1.7% 133  1  2 130   4730   6836   6    8  -67.3% 0.386
MOT17-09-FRCNN 0.7% 2.6% 0.4% 0.4% 2.9%  26  0  0  26    783   5302   0    0  -14.3% 0.283
MOT17-10-FRCNN 0.5% 0.3% 0.8% 1.5% 0.6%  57  0  0  57  31152  12646  56   67 -241.6% 0.429
MOT17-11-FRCNN 0.4% 0.5% 0.4% 0.4% 0.6%  75  0  0  75   7169   9394   4    1  -75.6% 0.428
MOT17-13-FRCNN 0.6% 0.4% 1.1% 2.2% 0.8% 110  0  3 107  30806  11388  68   69 -263.0% 0.413
OVERALL        0.6% 0.6% 0.6% 1.0% 1.0% 546  1  7 538 108429 111188 183  195  -95.7% 0.400

As you can see, the application was finished smoothly but I am wondering how come I get such bad results?
Any response is appreciated.

**Comment by timmeinhardt** [comment] 2020-03-08 18:56
Hello. Unfortunately we never encountered such behaviour. Can you double check if the you are running the correct `motmetrics==1.1.3` version? Another thing that I you could try is running the evaluation with `tracktor.write_images=True` and check the results in the corresponding output directory. Like this you can do a qualitative check of the results and see if the problem is due to the tracker or only the MOT metrics evaluation part at the end.

**Comment by zhichaolei** [comment] 2020-03-09 05:05
Hello,
Here's the results output by tracktor. I am thinking that the tracktor did not learn how to regress the location of targets correctly. I am using motmetrics==1.1.3 version.
![000100](https://user-images.githubusercontent.com/26703459/76184372-f01b7800-6188-11ea-853b-36246579149d.jpg)
Thanks for your response!

**Comment by timmeinhardt** [comment] 2020-03-09 12:53
Did you download the object detector model files as described in step 4 of the README.md?

**Comment by timmeinhardt** [comment] 2020-04-08 11:53
Can we close this issue?

**Comment by Nishzzz** [comment] 2020-05-12 11:17
> INFO - main - Initializing object detector.
> INFO - main - Tracking: MOT17-02-FRCNN
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 600/600 [03:48<00:00, 2.63it/s]
> INFO - main - Tracks found: 183
> INFO - main - Runtime for MOT17-02-FRCNN: 228.4 s.
> INFO - main - Writing predictions to: /home/zclei14/tracking_wo_bnw-master/output/tracktor/MOT17/Tracktor++
> INFO - main - Tracking: MOT17-04-FRCNN
> 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1050/1050 [06:44<00:00, 2.60it/s]
> INFO - main - Tracks found: 121
> INFO - main - Runtime for MOT17-04-FRCNN: 404.6 s.
> INFO - main - Writing predictions to: /home/zclei14/tracking_wo_bnw-master/output/tracktor/MOT17/Tracktor++
> INFO - main - Tracking: MOT17-05-FRCNN
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 837/837 [02:21<00:00, 5.90it/s]
> INFO - main - Tracks found: 62
> INFO - main - Runtime for MOT17-05-FRCNN: 142.0 s.
> INFO - main - Writing predictions to: /home/zclei14/tracking_wo_bnw-master/output/tracktor/MOT17/Tracktor++
> INFO - main - Tracking: MOT17-09-FRCNN
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 525/525 [03:17<00:00, 2.66it/s]
> INFO - main - Tracks found: 7
> INFO - main - Runtime for MOT17-09-FRCNN: 197.5 s.
> INFO - main - Writing predictions to: /home/zclei14/tracking_wo_bnw-master/output/tracktor/MOT17/Tracktor++
> INFO - main - Tracking: MOT17-10-FRCNN
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 654/654 [05:57<00:00, 1.83it/s]
> INFO - main - Tracks found: 313
> INFO - main - Runtime for MOT17-10-FRCNN: 357.5 s.
> INFO - main - Writing predictions to: /home/zclei14/tracking_wo_bnw-master/output/tracktor/MOT17/Tracktor++
> INFO - main - Tracking: MOT17-11-FRCNN
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 900/900 [07:55<00:00, 1.89it/s]
> INFO - main - Tracks found: 89
> INFO - main - Runtime for MOT17-11-FRCNN: 475.7 s.
> INFO - main - Writing predictions to: /home/zclei14/tracking_wo_bnw-master/output/tracktor/MOT17/Tracktor++
> INFO - main - Tracking: MOT17-13-FRCNN
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 750/750 [09:01<00:00, 1.39it/s]
> INFO - main - Tracks found: 460
> INFO - main - Runtime for MOT17-13-FRCNN: 541.5 s.
> INFO - main - Writing predictions to: /home/zclei14/tracking_wo_bnw-master/output/tracktor/MOT17/Tracktor++
> INFO - main - Tracking runtime for all sequences (without evaluation or image writing): 2347.1 s (2.3 Hz)
> /home/zclei14/anaconda3/lib/python3.6/site-packages/motmetrics/mot.py:243: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
> idx = pd.MultiIndex(levels=[[],[]], labels=[[],[]], names=['FrameId','Event'])
> IDF1 IDP IDR Rcll Prcn GT MT PT ML FP FN IDs FM MOTA MOTP
> MOT17-02-FRCNN 1.3% 1.2% 1.4% 2.1% 1.9% 62 0 0 62 19961 18189 32 33 -105.5% 0.386
> MOT17-04-FRCNN 0.1% 0.3% 0.1% 0.3% 0.9% 83 0 2 81 13828 47433 17 17 -28.9% 0.391
> MOT17-05-FRCNN 1.1% 1.3% 0.9% 1.2% 1.7% 133 1 2 130 4730 6836 6 8 -67.3% 0.386
> MOT17-09-FRCNN 0.7% 2.6% 0.4% 0.4% 2.9% 26 0 0 26 783 5302 0 0 -14.3% 0.283
> MOT17-10-FRCNN 0.5% 0.3% 0.8% 1.5% 0.6% 57 0 0 57 31152 12646 56 67 -241.6% 0.429
> MOT17-11-FRCNN 0.4% 0.5% 0.4% 0.4% 0.6% 75 0 0 75 7169 9394 4 1 -75.6% 0.428
> MOT17-13-FRCNN 0.6% 0.4% 1.1% 2.2% 0.8% 110 0 3 107 30806 11388 68 69 -263.0% 0.413
> OVERALL 0.6% 0.6% 0.6% 1.0% 1.0% 546 1 7 538 108429 111188 183 195 -95.7% 0.400
> 
> As you can see, the application was finished smoothly but I am wondering how come I get such bad results?
> Any response is appreciated.

I've seen this happen with many trackers. I am using the DeepSort tracker and when I run the evaluation script, I get the same results. I was hoping I could use this tracker. But I see the same problem here as well. Any idea what is happening and what I'm doing wrong?

**Comment by zhichaolei** [comment] 2020-05-12 11:20
Hello,
Sorry for the late reply. Please close this issue.

Best,
Zhichao

Nishzzz <notifications@github.com>于2020年5月12日 周二上午4:18写道：

**Comment by timmeinhardt** [comment] 2020-05-12 11:27
@Nishzzz Have you tried my suggestions from above?

**Closed** 2020-06-15 12:15 UTC
