### ISSUE TITLE
IndexError:cannot do a non-empty take from an empty axes.

### ISSUE THREAD

**Issue by Sun-101** [phil-bergmann/tracking_wo_bnw#68] opened 2020-03-24 08:57 UTC
hi
When I run test_tractor.py,I ran into this problem in the picture.
![1](https://user-images.githubusercontent.com/51768028/77408729-1f6dee00-6df3-11ea-8f4b-6da132c99d30.png)
My data set is placed in the way of MOT17Det.
I need to track pigs. I already have the gt.txt and det.txt file.Do I need to retrain the target detector？In addition, MOT17Det does not seem to use the det.txt file.
I don't know what caused the mistake.
I look forward to your reply.Thank you!

**Comment by timmeinhardt** [comment] 2020-03-24 10:05
Tracktor does not find any tracks for either of the two sequences. Thats why the evaluation fails. I will fix this soon. However, the reason for not finding any tracks at all is something you have to figure out. Depending on your dataset, the Faster RCNN of Tracktor has to be retrained. It is trained to detect pedestrians and not pigs. :)

**Comment by Sun-101** [comment] 2020-03-24 10:13
Retraining tracker which file do I need to run? Is it train_reid.py?

**Comment by timmeinhardt** [comment] 2020-03-24 11:05
Please have a look at the README.md. There is a link to a Google Colab which we used to train the object detector. You can use the same and modify it for your dataset and retrain the object detector.

**Comment by Sun-101** [comment] 2020-03-24 11:07
ok.Thanks again.

**Comment by Sun-101** [comment] 2020-04-01 00:31
HI，
I have retrained the object detector and output the results（model_epoch_27.model）. But there are still problems in the picture. Do I need to modify the parameters in test_tractor or other things?Or can I use the results(MOT17-01.txt，.....，...) of the object detector directly to evaluate?

**Comment by timmeinhardt** [comment] 2020-04-08 11:54
You can use the *.txt files to evaluate. But what do you mean by "problems in the picture"?

**Comment by Sun-101** [comment] 2020-04-08 13:04
That's the picture from my first question.
I've retrained the object detector.But it's still a problem.Tracks found:0

**Comment by timmeinhardt** [comment] 2020-04-08 14:22
What happens if you run our code on the original MOT dataset with our object detector? Can u reproduce the results reported in the repository? If the zero tracks error only occurs on your dataset you have to debug your dataset and training. Did you achieve a good object detection performance after training the detector?

**Comment by Sun-101** [comment] 2020-04-09 00:17
I have successfully trained and tested the original mot data set and output *. TXT results. But I can't test on my own dataset. I have used my own data set for object detector training and train_reid.py training. But I always encountered an error: tracks found:0 and the output *. TXT is empty.The object detector has achieved a good result.

**Comment by Sun-101** [comment] 2020-04-09 00:55
When I debug, I find that the result of results = tracker.get_results() is an empty dictionary.
![image](https://user-images.githubusercontent.com/51768028/78846455-6b00d880-7a3e-11ea-91af-e9e5dfa85960.png)
I looked at the functions it defined.
![image](https://user-images.githubusercontent.com/51768028/78846500-9388d280-7a3e-11ea-996e-7741028bb9b4.png)
Self.result itself is defined as an empty list. In the original mot dataset, this function has a numerical value, but in my own data set, it is 0. I don't know how this result is loaded or written.

**Comment by Sun-101** [comment] 2020-04-12 11:52
I have solved this problem! The reason for this problem is that no det file was found. I reconfigured the folder to solve this problem. Thank you very much for your help!Have a nice day!

**Comment by timmeinhardt** [comment] 2020-04-14 10:24
Sounds great! We hope the repository helps you with your project. Can we close this issue?

**Comment by Sun-101** [comment] 2020-04-14 10:26
Yes, of course.

**Closed** 2020-04-14 10:27 UTC
